# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: وب سایت شخصی فاطمه سادات شفیعی
author: فاطمه سادات شفیعی
email: sadat.shafiei@gmail.com
keywords: "، asp.net,کامپیوتر، برنامه‌نویسی، جاوا، پی اچ پی، سی شارپ"
copyright: "فاطمه سادات شفیعی"
description: > # فاطمه سادات شفیعی هستم!
    به برنامه نویسی علاقه زیادی دارم!
    در این وب سایت سعی می کنم تجربیات هر چند اندک خودم رو در زمینه طراحی سایت با jekyll به اشتراک بزارم .
 
    بهترین ها رو برای شما آرزو می کنم
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sadat-shafiei.ir" # the base hostname & protocol for your site
twitter_username:
github_username:  sadatsh

favicon: "img/favicon.png"

# Build settings
markdown: kramdown
kramdown:
    coderay_line_numbers: 1
encoding: utf-8
timezone: Asia/Tehran

gems:
  - jekyll-sitemap
#  - jalalidate - coderay
  
